### ISSUE TITLE
Deleting groups makes program unusable

### ISSUE THREAD

**Issue by TaulantZ** [Dudrie/Tutor-Management-System#111] opened 2019-10-21 07:45 UTC
When deleting a group while people are in it,
the dashboard as well as overview won't load up, making the program unusable.
# :heavy_check_mark: Expected behaviour
Site loads up. People who had been assigned to the deleted group shouldn't be assigned to any group.

# ⚡ Actual behaviour 
Loading screen won't stop.

# :joystick: Steps to reproduce
Add student and assign to group.
Delete group.

![Firefox_Screenshot_2019-10-21T07-43-35 387Z](https://user-images.githubusercontent.com/56818059/67186046-7ce6b480-f3e7-11e9-877e-7c939ff8d64a.png)

**Comment by Dudrie** [comment] 2019-10-21 09:56
I can't reproduce the issue right now. However it could be that this happened due to the server being unavailable (due to an update). 

Can you reproduce the bug right now? 

However, this issue is important for something else: There need to be more failure messages visible to the user 🤔

**Comment by Dudrie** [comment] 2019-10-21 10:15
After further investigations in the production system it seems your tutorial is in an inconsistent state (sorry for that). We are working on a fix for the database.

**Comment by Dudrie** [comment] 2019-10-21 19:34
This should be fixed in #114.

**Closed** 2019-10-22 20:29 UTC
Labels: bug, fixed in PR
